# Generated by Django 5.2.17 on 2026-09-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_detalleventa_venta_productos_perfilcliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('densidad_poblacional', models.PositiveIntegerField()),
                ('flujo_personas', models.CharField(max_length=20)),
                ('accesibilidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('distancia_metros', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmacias', to='farmacia.zona')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inkafarmas_cercanos', models.PositiveIntegerField()),
                ('competidores_cercanos', models.PositiveIntegerField()),
                ('centros_salud_cercanos', models.PositiveIntegerField()),
                ('costo_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ventas_estimadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_viabilidad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='farmacia.zona')),
            ],
        ),
    ]
